### ISSUE TITLE
Need GitHub Action to check book code

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafrocBook#29]
Peter said: 

https://github.com/dpc10ster/RJafroc/issues/59#issuecomment-739102165

Need to automate `RJafrocBook` checks that formerly were in Travis, and post website from `doc`. But how about pdf build? That sometimes catches errors missed by git build.

**Comment by pwep** [comment]
I've got a work in progress branch called [`migrate-to-gh-actions`](https://github.com/pwep/RJafrocBook/tree/migrate-to-gh-actions) in my fork of RJafrocBook.

**Comment by dpc10ster** [comment]
OK; I have manually merged your change(s) into` developer` (I was missing the pkgdown.yaml file in my `.github/workflows`) and pushed the `developer` branch. it seems to be working. Curious: the directions said the contents of `.pkgdown.yaml` was optional. I have seen one example of an empty file.

I can delete the issue I just posted.’

**Comment by dpc10ster** [comment]
I took a stab at it; the `yaml` file is from a [link](https://ropenscilabs.github.io/actions_sandbox/websites-using-pkgdown-bookdown-and-blogdown.html#deploy-bookdown) you sent me. It failed with a message that `ggplot2` was not available or loaded;

**Comment by dpc10ster** [comment]
Just added a `_pkgdown.yaml` file in root. Should it be called `_bookdown.yaml`? At least it is still running after about 17 min. Previously it failed almost immediately. Gops, just found out (21 min) it failed with same `ggplot2` error message.

**Comment by dpc10ster** [comment]
Adding `ggplot2` to `deploy_bookdown.yaml` took away that error and got a new error for missing `kableExtra`; so I added all dependencies;

`Rscript -e 'install.packages(c("rmarkdown","bookdown","ggplot2","kableExtra","abind","dplyr","grid","gridExtra","pBrackets","RJafroc","seqinr"))'

Why??

**Comment by dpc10ster** [comment]
More progress; but failed with following message:

```
Quitting from lines 713-724 (06-binormal-model.Rmd) 
813
Error in Df2RJafrocDataset(K1t, K2t, InputIsCountsTable = TRUE) : 
814
  unknown data type

```

Checked that part of code; cannot figure out why it failed.

**Comment by dpc10ster** [comment]
Progress; but it expects files to be in `_book` when in fact they are in `book`. Changed `_book` to `book` in the `yaml` file.

**Comment by pwep** [comment]
Nearly there. The latest error is due to an unverified email. Looking at the deployment process from an RJafroc action and from the RJafrocBook `_deploy.sh` file, I'm trying the following in the ` checkout-and-deploy` section of the action (which appears to work).

```
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: docs # optional
          # Destination path
          path: docs # optional
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: book-output
      - name: Upload artifact
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # git clone -b gh-pages book-output
          cd book-output
          cp -r ../docs/* ./
          git add --all *
          git commit -m "Update the book" || true
          git push -q origin gh-pages
```
